In [38]:
# Load Datasets
import pandas as pd
import networkx as nx
df = pd.read_csv("/Users/laleshkumar/Python_course/PageRank/endorsement_network.csv")
df.head()

            endorser         endorsed  weight
0  A.S.R.S.S Snigdha     Bhoomi Gupta       1
1  A.S.R.S.S Snigdha   C LOHITH KUMAR       1
2  A.S.R.S.S Snigdha     Krishanu Das       1
3  A.S.R.S.S Snigdha      Rekha Battu       1
4  A.S.R.S.S Snigdha  S.S.S.Venkatesh       2

In [39]:
df.describe()

            weight
count  1762.000000
mean      1.024404
std       0.154344
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       2.000000

In [40]:
df["weight"].value_counts()

weight
1    1719
2      43
Name: count, dtype: int64

In [41]:
df["endorser"].nunique()

408

In [42]:
df["endorsed"].nunique()

461

In [43]:
endorse_count = (
    df.groupby("endorser")["endorsed"]
      .nunique()
      .reset_index(name="count")
      .sort_values("count", ascending=False)
)
print(endorse_count.head())

           endorser  count
53    Ansh Varshney     33
7        AMAN SAGAR     24
140     Hanya Batra     21
176    Kajal Kumari     21
114  Devika Nambiar     20

In [44]:
endorsed_count  =(
    df.groupby("endorsed")["endorser"]
    .nunique()
    .reset_index(name="count")
    .sort_values("count",ascending=False)
)
print(endorsed_count.head())

                 endorsed  count
339  Sai Akshay Oggisetty     27
37              Agam Sahu     25
154           Hanya Batra     21
125        Devika Nambiar     19
53         Animesh Pathak     18

In [45]:
df[df["endorsed"]=="Ansh Varshney"].count()

endorser    14
endorsed    14
weight      14
dtype: int64

In [46]:
df[df["endorsed"]=="Sai Akshay Oggisetty"].count()

endorser    27
endorsed    27
weight      27
dtype: int64

In [47]:
df = pd.read_csv("endorsement_network.csv")
G = nx.from_pandas_edgelist(
    df,
    source="endorser",
    target="endorsed",
    edge_attr="weight",
    create_using=nx.DiGraph()
)

In [48]:
print(G)

DiGraph with 475 nodes and 1762 edges

In [ ]:
pagerank_scores = nx.pagerank(
    G,
    alpha=0.85,
    weight="weight"
)

{'A.S.R.S.S Snigdha': 0.0023108851679946424, 'Bhoomi Gupta': 0.0008794612999374345, 'C LOHITH KUMAR': 0.0010788854302924567, 'Krishanu Das': 0.0008644437388373375, 'Rekha Battu': 0.0011689814037302581, 'S.S.S.Venkatesh': 0.0011326745430996236, 'Shreya Sunil Habib': 0.000711457582957997, 'ABHAY KUMAR SHARMA': 0.003560405540743994, 'Joyita Bhawal': 0.0034556126971440936, 'ABHIROOP MUKHERJEE': 0.004236526304841926, 'Agam Sahu': 0.00559052430066886, 'Anjana Jagiram': 0.0027894744937226245, 'Arfa Ahmed Ansari': 0.0038128004482580924, 'Aryan Pophali': 0.002350025292265665, 'Chirashri Karmakar': 0.0009517383831939482, 'Esarapu Gautham': 0.0009269457704192415, 'Hritam Das': 0.0008263579417232557, 'Mohd Adil': 0.0020620573908929074, 'Rajat Sharan': 0.0014851569031708142, 'Rohit Guchhait': 0.0038204789885355212, 'SUBHAJIT SAMAJPATI': 0.0008263579417232557, 'Sampurna Chakrabarty': 0.0006309213428645423, 'Shaik Nishad': 0.002342051828317388, 'Shubh dixit': 0.0065341748103953014, 'Soumi Sarkar': 0.004811118257345155, 'Suvanjan Das': 0.0029094429714664636, 'Tanusree Sadhukhan': 0.0014176443928157548, 'ADARSH VISHWAKARMA': 0.0013587783170134417, 'Abhi Sriya P': 0.0031386950905670495, 'Kashish Panwar': 0.0021877761724159034, 'SAMAD MOHAMMED': 0.006840765190839692, 'Shreya Choudhary': 0.0019570342896480727, 'Vandan Bhardwaj': 0.0010495996818882902, 'ADHARSH K': 0.0010927499069760954, 'Abinivesh M': 0.0005635274484885396, 'Animesh Pathak': 0.0058355138937679525, 'K Sivaramakrishnan': 0.0008859441039481194, 'Madhu S': 0.0005635274484885396, 'Swasti Jain': 0.001203877464021013, 'Tharunika Natarajan': 0.0011077458733496938, 'ADITYA GUPTA': 0.000846963479883203, 'Aashu Goswami': 0.003425951154937878, 'Durva Jain': 0.000670842984679944, 'kukkala.Tejupriya': 0.0009559947388337352, 'ALLU SAI SAMHITH REDDY': 0.003118659329112139, 'Joel Joseph Philip': 0.007137799391774104, 'AMAN SAGAR': 0.005072809239293526, 'ANJALI SINGH': 0.0032727095156759086, 'ARUNACHALAM V': 0.003853142438969707, 'ASHUTOSH AVDHESH NAYAK': 0.0017022508785135984, 'Aditya Raghuvanshi': 0.003214822885126203, 'Arpita Patnaik': 0.00225675343848365, 'Devanshi Mittal': 0.0034711714247615483, 'Druhi Chakraborty': 0.007474400080906012, 'Harish Saini': 0.0021799697044001293, 'Jandhyala Uma Sri Lekha': 0.001832243702189419, 'Jinal Gupta': 0.0010274920218893415, 'MUDIMADUGULA SRIJA': 0.0009490188281326044, 'Mohamed Asif': 0.002222553566149414, 'Sai Akshay Oggisetty': 0.010298327084654942, 'Samruddhi Kishore Savane': 0.0010856047793486663, 'Sheharba Siyab': 0.0031824949494792796, 'Shreyas Mene': 0.008037617132711818, 'Vishal Paraji Autade': 0.003106971121422028, 'tanvish desai': 0.0021305925697639345, 'ANJALI BINGI': 0.003495924215949486, 'DRAKSHAYANI RAYAPARTHY': 0.003598080754637322, 'Maragoni Harini': 0.004311931162328513, 'kirti solanki': 0.003733759150242302, 'Ankita Maji': 0.0011264388865544466, 'Gadamsetti Tvisha Aditi': 0.0020240582736551823, 'ANUSHKA JAISWAL': 0.002744415571289313, 'Abhishek Yadav': 0.0024583465847908092, 'Devika Nambiar': 0.007923855581479573, 'Dhruvi Jatinkumar Shah': 0.0018327771475890524, 'Mansi Singh': 0.002518973114126751, 'Nada Waris Gilani': 0.0031260081582795605, 'Piyush Yadav': 0.0024312424881784114, 'Radhika Sharma': 0.0037547641742606977, 'ARIJIT DEB': 0.0016395970361380197, 'Abhi Mishra': 0.003344178114807533, 'Bikash Samanta': 0.0012512706684846405, 'Gurnoor Singh': 0.003467212587278601, 'HARSHITHA PENTELA': 0.002098069831433997, 'Pradeep Gupta': 0.003525145582781746, 'SHUSHANT PATEL': 0.0007262728020775615, 'Saniya Singh': 0.0008581975317920081, 'ARNAB BANERJEE': 0.0011494920653646098, 'Jatin Kumar 1': 0.002690028030293471, 'Remy Baastin Rayappan': 0.0008983901794156045, 'PANDRAJU POORVI PRAVALLIKA': 0.00500963931912988, 'ARUNADITYA RAGURAMAN': 0.0035928957432383108, 'Aarsh Sohane': 0.0017069871311828815, 'Ananya Kumari': 0.0026117728480717826, 'Aryan Vaghasiya': 0.0016190706439631903, 'Harsh Joshi': 0.0017848572384147705, 'Keerthana Thippana': 0.0016495033961186263, 'Devansh Chourasia': 0.0023528214279819348, 'ATHIRA K V': 0.0024427796559175746, 'Ahana Banerjee': 0.0032422203716724616, 'Jeff Jacob Mathew': 0.0016844708917894673, 'M S Harshitha': 0.003300745441533658, 'Nandula Lakshmi Varshini': 0.0031636875570733207, 'Priyanshu Kumar': 0.004953627582026109, 'S Shrinidhi Sharma': 0.0008084018816595721, 'Shreejal Nagesh Bangera': 0.001496848174073106, 'Tetala Rukmender Reddy': 0.003984692022180234, 'Aarushi Chakraborty': 0.0007412581720659671, 'Kalyanam Venkata Narayana Hasith': 0.0007617791423091733, 'Malluri Archana': 0.0017243790334464655, 'Manish Panda': 0.0008987952490679761, 'Vanshika sambher': 0.0006829313964185237, 'Anshika Saraswat': 0.00312225236297741, 'DHEERAJ M G': 0.001933314032684129, 'Gurmehakdeep Singh': 0.003028724969528551, 'Kanakashree': 0.000846963479883203, 'Shreya S Salian': 0.001418243752515696, 'Thota Venkata Avinash Naidu': 0.0033593535417824455, 'Abhi Kiskorkumar Patel': 0.0012479764212739546, 'Jain Akins Dharmesh': 0.0009612499155903544, 'Achintya Srivastava': 0.004698331574153172, 'Lovepreet': 0.001726865742672977, 'Somya Kapoor': 0.0017672810835621302, 'Abhishek Avasthi': 0.005942181511497979, 'Majjiga Harshitha': 0.0011345028179827058, 'Nimish Ratan Tilwani': 0.0055826498504752695, 'shlok jangid': 0.0056682326503523905, 'Abhijith B': 0.0020007492435003705, 'Anurag PS': 0.004998785541782877, 'Dhanshree Gaur': 0.003709686652176486, 'SREYA S': 0.0022420657476164133, 'Avinash': 0.004524919757643203, 'Abhishek Kumar 1': 0.0011913906000809967, 'Ashish Patel': 0.0011256254223663302, 'Ganesh Prabu': 0.0011256254223663302, 'Mikki Jhuria': 0.000684015527964766, 'Pritam': 0.0014426179010560117, 'Abhishek Kumar 2': 0.0006444741281425365, 'Vedhiga V B': 0.001256711268548565, 'Antra Agrawal': 0.0031516862250276444, 'AnujYadav': 0.0012299821861493365, 'Bhargav Dixit': 0.0021234744715351857, 'Shatakshi': 0.006206217698431359, 'Adarsh Dixit': 0.003144313481654752, 'Ansh gangwar': 0.0022689321391000626, 'Devanshu Kumar': 0.0041876035471975215, 'Khushi Dhona': 0.005136800769704282, 'Lakshya Agarwal': 0.0028909784056191956, 'Pari Jain': 0.002344040718387749, 'ROHIT B LAKSHMANAN': 0.0024301804059186183, 'Aditi Gupta': 0.0017504547546238112, 'Aditi Tomar': 0.0028582470789027606, 'Anshika Tomar': 0.0028582470789027606, 'Kanika gupta': 0.0027049819076595716, 'Nandani': 0.0015069197049015696, 'Divyadharshini S': 0.002592558949923718, 'Thivesha M S': 0.003284424267268592, 'Agniprobho Das': 0.0004308103013739742, 'Debajyoti Ghorai': 0.0010677390963393502, 'SHREYASI MAITI': 0.0010677390963393502, 'K C Dharshan': 0.0031753854478165883, 'Akash Kumhar': 0.002253693429277671, 'Ansh Varshney': 0.005597568485360669, 'Aryan Banarjee': 0.0027081051609957555, 'Akella Hasitha': 0.0032115591493660223, 'Debosruti Datta': 0.000885648332182362, 'MALLADI GAYATHRI HARIPRIYA': 0.002812135740213216, 'Meda Vyshnavi': 0.0027135895696266416, 'Neelam Venkata Durga Phaneendra': 0.002812135740213216, 'Sarikonda Durga Bhavani': 0.002812135740213216, 'mounika surnar': 0.002319404887280344, 'Akshat Sharma': 0.003420875345825652, 'Anshika Pathak': 0.0020177619708667063, 'Anuj Pratap Singh': 0.0011252348711882345, 'Ashish Kushwaha': 0.002574618351411779, 'Hanya Batra': 0.007600045023920386, 'Juilee Lambe': 0.005342062409441407, 'Kajal Kumari': 0.00389530700188795, 'Khushi Choudhary': 0.004795146646471802, 'Konark Garg': 0.002983555542182376, 'Pawan Kumar': 0.0006018965001537311, 'Writwik Das': 0.002639764140048989, 'YASHHWANTH PAYYAVULA': 0.005507529928463695, 'Aman Jaiswal': 0.0006687774206562277, 'Aravinth K': 0.0025385684286272268, 'Ambadipudi Akhila Sai': 0.002006270121504558, 'joginapally sumani goud': 0.0037102240363009616, 'Ambati vedanandana': 0.0019850579313120367, 'DISHI GUPTA': 0.0019898430484644324, 'Hasti Lakhani': 0.002027098288906482, 'Mano Shruthi S': 0.0025814452460148213, 'Amirth Sadhakshi M': 0.0018281916463374114, 'Drakasharam Rushali': 0.000572106112300675, 'Khushi Dosi': 0.000572106112300675, 'Kiran Satish Belsare': 0.0010584467053447468, 'M. Lakshmi Sahasra': 0.0008189251134533064, 'OMAR SHAIK': 0.0029029622275996547, 'Sukrish': 0.0009202102704194236, 'VENKATA SAI PAVAN VETCHA': 0.000572106112300675, 'Amit kumar khatri': 0.0010065356356104714, 'Amritanshu Mishra': 0.002390492750921151, 'Beldhari Swapna': 0.004348029102293368, 'Saniya Jose': 0.001523484761583183, 'Vennela Pilla': 0.0024414991135681273, 'Anant Pratap Singh Tomar': 0.0012098882450029347, 'Anugrah Bhardwaj': 0.0011674715090315578, 'SAHIL 1': 0.0006365419528154517, 'Siddharth Rai': 0.0006365419528154517, 'Yash Chouhan': 0.0006365419528154517, 'Anant Raj Saxena': 0.003888859583018188, 'ankita chaudhary': 0.004071965467667151, 'Lavkush': 0.0039285641490470775, 'Vedhanth M': 0.001440789963527797, 'Ananya singh': 0.0010835471454109758, 'Lakshya Gupta': 0.0023031989301056867, 'Divyanshi jain': 0.003481288026267934, 'Ankita Agrahari': 0.0013037759532424829, 'Vanisha Tiwari': 0.0026408513947608772, 'Sharonya Banerjee': 0.005064863464582468, 'Vidhi Luniya': 0.0015614108897813181, 'Yazhini Parthasarathy Lakshmi': 0.0021560322474535485, 'Chirag Saxena': 0.0006693648980722485, 'Kratika Varshney': 0.0010144606442241502, 'MUDIT AGRAWAL': 0.0016091308333964814, 'Manish Patel': 0.0034052060831634397, 'Prashik Prabudha Kadam': 0.0019042058435368328, 'Shashwat Singh': 0.0005441324004506911, 'Sheetal': 0.0013737466736889288, 'Udarsh Goyal': 0.0005441324004506911, 'Vidyagouri Kulkarni': 0.001977663982823945, 'Namrata Saha': 0.0010866652828828564, 'KONDA POOJITHA': 0.002964352416602725, 'KRITHIKAA B': 0.0009617398575900803, 'Anshul Kanodia': 0.0004308103013739742, 'Bhakti sudhir kadam': 0.001869213895166861, 'Anwesha Ghosh': 0.0012202188568674994, 'Archit Singh': 0.0004308103013739742, 'Yash Parmar': 0.004432145679248965, 'R Yeshwanth': 0.0010989100229424856, 'Arni Johry': 0.0008372479618970139, 'Priteenanda Das': 0.0005784034550522705, 'Muskan Kumari': 0.001634214741884014, 'Pinjar Ayesha Anjuma': 0.0012733060545468812, 'Aryan Srivastava': 0.0004308103013739742, 'Aryan Vishala': 0.0015671929878248191, 'Nirainthan Ravi': 0.0017632673503061099, 'Lakshya Aran': 0.0024003112450179105, 'Ashish Patra': 0.0028582470789027606, 'Vishal Kumar': 0.0028582470789027606, 'Ashwani Kumar Gautam': 0.0005885161156464896, 'Atul Mishra': 0.0012882526681295158, 'Kundan Kumar': 0.0017419726747099052, 'Lokesh Kumar Garg': 0.0014240797879618385, 'Ayush Kochhar': 0.0028582470789027606, 'Garv': 0.0028582470789027606, 'BADALA SHRAVYA REDDY': 0.0004308103013739742, 'BIPIN TIWARI': 0.0016631353232875036, 'Deepesh Gupta': 0.0018169535454781519, 'Dharma Raju Garaga': 0.0017351793213118308, 'Dhinith Pragalyan M': 0.0005721997191311477, 'Mavyatha Paireddy': 0.0016091023247692582, 'Muddagowni kavitha': 0.0008374706253195935, 'Sai Manikanta': 0.0011022384613278585, 'Vedulla Sampath Gyana Teja': 0.0011657656962988645, 'Balne Aishwarya': 0.0010499221854935546, 'Boeni Poojitha': 0.0014612636136066932, 'Chidura Tejasri': 0.0007283105397578674, 'Neeraja Bapatla': 0.0007283105397578674, 'Bheemarapu Sathvik': 0.0014462359577071312, 'Harsha Thilak M': 0.0017191053639162971, 'Korrapati Neha': 0.004824059219523283, 'Modala Prasanna Kumari': 0.001697951719171986, 'Dev kushwah': 0.0010328698870024446, 'Bhavya Jain': 0.0028582470789027606, 'Kavya Agarwal': 0.0028582470789027606, 'Irfana': 0.0007420139561425917, 'Mannat Balyan': 0.0011723878224475016, 'Mehak Gupta': 0.001522111431131685, 'Rachit Verma': 0.0007412581720659671, 'Harshita Singh': 0.0009726269563354612, 'Bhoomika Agarwal': 0.0011301641395432373, 'Sahitya Kumar': 0.003914640728375783, 'Bithika Jain': 0.0027247096659872025, 'Chandragiri Sai Tharun': 0.0031771727831111643, 'Boini Kavya': 0.0028582470789027606, 'Maheshwaram shireesha': 0.0028582470789027606, 'Bramhesh Chandrakant Patil': 0.0020097539669266954, 'Jigar Virbhadranath Vyas': 0.001285045861680246, 'CHINMAY SHARMA': 0.0013227238605169377, 'Rajan': 0.0011358503168606995, 'Samarth Srivastava': 0.0014790258005644, 'Syamala Umesh Sai Hanuma Prasad': 0.003351617740931742, 'Chandana Jagadish': 0.0026639344232248746, 'Penugonda Deepthi': 0.0032223887477350723, 'Shaik Mohammed Zahoor Ahmed': 0.0035227156286734658, 'kudimi Rohith': 0.003907405831559816, 'Cheedella Sai Nikhil': 0.0037102240363009616, 'Ritwij Tripathi': 0.002006270121504558, 'DODDI VENKATA KANAKA MAHALAKSHMI': 0.0029118371929851552, 'IDDUMU JYOTHIKA': 0.0029118371929851552, 'MOHAMMED SHAHID AZEEZ': 0.0043969255044169165, 'Raksha S': 0.0028876389056220696, 'Tushit Tiwari': 0.002354148208817203, 'Vadde Nandeeshwari': 0.0026026806573477986, 'DUSI KEERTHI PRASANNA': 0.0008556157795943748, 'Damanpreet Singh': 0.0019046752469964968, 'Deepti': 0.0005988140183534116, 'Dhruv': 0.0005580680129152489, 'Harshit Sharma': 0.0005580680129152489, 'Kesar Agrawal': 0.0009983718250158678, 'Suhani': 0.000907871769387048, 'Penumaka Sharvani Shriya': 0.002052512250886808, 'Nitin Singh': 0.0008263619770732902, 'Jinendran S': 0.002080199108015419, 'Poorti Swarup': 0.004886062384203368, 'Tanishka Sharma': 0.0009672445854705428, 'Jatin Bansal': 0.0029752231093392602, 'Dikshya Soni': 0.0028582470789027606, 'Vishal Soni': 0.0028582470789027606, 'Dipankar Banerjee': 0.0007097114962262941, 'DIPTOSUBHRO DATTA': 0.0009821159685319664, 'Rachit S Mane': 0.0005514718658543035, 'Disha Bansal': 0.0028582470789027606, 'Harsh. Gupta': 0.0028582470789027606, 'Rashmi Risha J': 0.002212064926752568, 'Vanshika Agrawal': 0.0021100556793364525, 'Divyansh Singh': 0.0007918957077109052, 'Garvit Bansal': 0.0014651271585560204, 'Shristi': 0.0012509114442941323, 'Harshita Balchandani': 0.0027224518189268025, 'G. Ramyashree': 0.0018020653514026533, 'PRABHA T R': 0.003226379933351615, 'GOPARAJU DEEPIKA': 0.0017415682334678498, 'Sneha Maity': 0.000800947182131559, 'Vipaturu Akhila': 0.0011413920009072584, 'Ginne Manaswi': 0.0018020653514026533, 'Anshika tyagi': 0.001963704228460318, 'Govind Khandelwal': 0.0007970220706719038, 'jasdeep kaur': 0.0014092694002691458, 'HARIHARAN SUBRAMANYAN': 0.0004308103013739742, 'S. Sai Sanjana': 0.0004918455962569624, 'Y SRI SAI SATHVIKA': 0.0005528808911399506, 'Ananya Agarwal': 0.0008308978042591584, 'Harsh Aggarwal': 0.0010309609905669818, 'Harsh Kumar': 0.0012549359713485502, 'Harshdeep': 0.000663984355538384, 'Harshit Agarwal': 0.002206496772481523, 'Lalesh Kumar Raj': 0.002450131921792614, 'Mohammad Sahil Ansari': 0.002450131921792614, 'Kollipara Naga Harshitha': 0.0024726894136754022, 'Priyanjali Chaudhary': 0.0028621579645771323, 'Ridha n': 0.005028248752261647, 'Sri Tejaswi putta': 0.003461719233134025, 'TANU VATS': 0.0024726894136754022, 'Yalampalli Varshini': 0.0024128139980266823, 'Shreya Agnihotri': 0.0010122211291439225, 'Shreya Sharma': 0.0014899547750451265, 'Hemanth Kumar Reddy Tallapureddy': 0.002192205956240278, 'Simran': 0.002592861491983274, 'Sumit Dhakar': 0.0021922059562402784, 'Himanshu Yadav': 0.00127403545758052, 'Hitesh Binjrawat': 0.0028582470789027606, 'Sameer mishra': 0.0028582470789027606, 'Om Desai': 0.0023828385944234696, 'Saniya Asreen': 0.0005096580472646238, 'Tarun kumar': 0.0011537939137799408, 'makka archana kumari': 0.0005096580472646238, 'Jagriti Sahu': 0.0006974810235725115, 'Sarthak Gupta': 0.001254783578591795, 'Joyce Josphin Quenie .P .R': 0.00127403545758052, 'Hamsa Varshini S': 0.0011931064873065638, 'Jatin Prajapati': 0.0012715271157141873, 'Ayush Sharma': 0.0008520015124829723, 'Shrikant Sharma': 0.0007255583967243795, 'Tirtha Jhaveri': 0.0010411567414993195, 'kevin R': 0.000936872195189148, 'Jiya Singh': 0.0010365757198029799, 'Obilisetti Thanishka': 0.0008851937735803498, 'SHAIK UJJEEF': 0.0009090081596626167, 'Sannoji Alekhya': 0.0007769108545790594, 'Kartik Nath Khatri': 0.0005885161156464896, 'NEELAM LOKENDRA BABU': 0.000574829911357556, 'Karan': 0.0024192997327713746, 'MD AARIZ FAROOQUI': 0.0013531476390500337, 'Rudraksh Mishra': 0.0007823517062786872, 'Kritika Sharma': 0.0028582470789027606, 'Utkarsh Verma': 0.0028582470789027606, 'Kunal Badgujar': 0.0028582470789027606, 'Sukrut Ujwal Dusane': 0.0028582470789027606, 'Mohammed Sameer Inamdar': 0.001819688129531206, 'Mayank Garg': 0.0019266244005410062, 'Siddhant Sharma': 0.0025427565535882965, 'Lois A Johnson': 0.0019055591237529881, 'Nishita Singh': 0.00504411697004247, 'Pragati Thakur': 0.0019055591237529881, 'Sartaj Singh': 0.00448185322952414, 'krish kagra': 0.002423993044655549, 'Rohit Desina': 0.0016754288969916945, 'Niranjan Praveen': 0.0031195388537407815, 'Madhav Rimal': 0.0009763147413763927, 'Manya Valecha': 0.0028582470789027606, 'Shaik Musqan Khadri': 0.0028582470789027606, 'Muralikrishnan N': 0.004278274482546146, 'Siddharth Tarunbhai Sadhu': 0.0027246002053035855, 'Neeraj Agrawal': 0.0028582470789027606, 'Shyam Sundar Sharma': 0.0028582470789027606, 'Yogesh Kumar Gupta': 0.0028582470789027606, 'Nikhil Sai Kenguri': 0.0007465207055443231, 'Shriya': 0.001114095313901172, 'Abhishek Chaubey': 0.000958116662121989, 'Prasoon Lawania': 0.0017675232404754096, 'SHANMUKHA SRI SAIKUMAR MEDISETTY': 0.0030758059046938875, 'Nitesh Verma': 0.0011794342576632805, 'Rapolu Vignesh': 0.002429055130449816, 'Rahul Thakur': 0.0015726343734216485, 'Velagada Udaykiran': 0.003497239771551533, 'Jatin Kumar 2': 0.0005499674246775507, 'Parnita': 0.0005499674246775507, 'Rohit Sharma': 0.0005499674246775507, 'Sarthak Patil': 0.0005499674246775507, 'Ritish Karmakar': 0.0015704307033686951, 'PATAN JAMSHEER': 0.0010568254174848878, 'PRAVEEN KUMAR P': 0.0013292141241182148, 'Pabba Sai Divya': 0.0011105524881340556, 'Payal': 0.0014449013068119636, 'Sanskriti Singh': 0.0035775412857553756, 'Pediredla Akhul Sri Sai Nandan': 0.0004308103013739742, 'M.BHAVYA SREE': 0.0007970220706719038, 'Piyush Kumar Sharma': 0.0006979764690520624, 'Bhimashri Deka': 0.0008957498383327403, 'Sarasam Chinmaee reddy': 0.0006285836706546521, 'Swati jain': 0.0007033047096460244, 'VAISHNAV BHARAT GOPALE': 0.004004907474583434, 'Puli Bharat': 0.0008459874509227064, 'Pulipaka Lakshmi Kanth': 0.0011500397659764158, 'Jasvider Kaur': 0.000660355944926405, 'Ranjan Gupta': 0.0004308103013739742, 'samridhi goyal': 0.0004918455962569624, 'Rangesh B': 0.0005399113674081815, 'Riddhima Kiran Deshmukh': 0.0008717519806420378, 'Soumaditya Deb': 0.0005399113674081815, 'Sulagna Chakrabarty': 0.0005399113674081815, 'Rishabh Rai': 0.001096377846338657, 'Rushikesh Vitthal Barge': 0.0038182096997022848, 'Sahil 2': 0.0004308103013739742, 'Sakshi': 0.0028582470789027606, 'VAIBHAV CHAUHAN': 0.0028582470789027606, 'Samarpit Gujral': 0.0004308103013739742, 'Tanushree T N': 0.0005629076064575314, 'Sarim Hussain': 0.0007283105397578674, 'Shashwat Srivastava': 0.0010499221854935546, 'Sarthak': 0.0028582470789027606, 'Vikas Boura': 0.0028582470789027606, 'Faiyaz Khokhar': 0.0006974810235725115, 'Arnab Mazumdar': 0.0008614544040516372, 'Shivang Chauhan': 0.0028582470789027606, 'Tanuj Bansal': 0.0028582470789027606, 'Abhijeet Janbandhu': 0.0009864328227872938, 'Arya Mistry': 0.0009864328227872938, 'Soor Soni': 0.0004308103013739742, 'Jugal Thakkar': 0.0007970220706719038, 'Sugriva Pardhava Ajith': 0.003270996698222411, 'Swati Kumari': 0.0004308103013739742, 'Tanisha Jain': 0.0021952641477476632, 'Varun Pal': 0.0016908819088542635, 'Uday Bhardwaj': 0.00075774418032106, 'Tejswini Tiwari': 0.0004308103013739742, 'Sumansh Yadav': 0.0005485314821149412, 'Vatsal Jaroli': 0.0005485314821149412, 'Utkarsh tiwari': 0.0028582470789027606, 'sumit pandey': 0.0028582470789027606, 'Ved Sojitra': 0.0004308103013739742, 'Prerna Pundir': 0.0006444741281425365, 'Abhishek Shukla': 0.0007626509146078304, 'Krish Choudhary': 0.0012112464237765783}

In [61]:
top_pr = (
    pd.DataFrame(
        pagerank_scores.items(),
        columns=["Person","PageRank"]
    )
    .sort_values(
        "PageRank",
        ascending=False
    )
)

print(top_pr.head())

                   Person  PageRank
59   Sai Akshay Oggisetty  0.010298
62           Shreyas Mene  0.008038
73         Devika Nambiar  0.007924
175           Hanya Batra  0.007600
53      Druhi Chakraborty  0.007474

In [62]:
in_degree = dict(G.in_degree())
top10_indegree = (
    pd.DataFrame(
        in_degree.items(),
        columns=["Person","InDegree"]
    )
    .sort_values(
        "InDegree",
        ascending=False
    )
    .head(10)
)

print(top10_indegree)

                   Person  InDegree
59   Sai Akshay Oggisetty        27
10              Agam Sahu        25
175           Hanya Batra        21
73         Devika Nambiar        19
35         Animesh Pathak        18
62           Shreyas Mene        17
24           Soumi Sarkar        17
30         SAMAD MOHAMMED        17
53      Druhi Chakraborty        16
12      Arfa Ahmed Ansari        16

## 7. Damping Factor

In [63]:
for alpha in [0.5,0.85,0.95]:

    pr = nx.pagerank(
        G,
        alpha=alpha,
        weight="weight"
    )

    top10 = (
        pd.DataFrame(
            pr.items(),
            columns=["Person","PR"]
        )
        .sort_values(
            "PR",
            ascending=False
        )
        .head(10)
    )

    print(f"\nAlpha={alpha}")
    print(top10)

Alpha=0.5
                   Person        PR
59   Sai Akshay Oggisetty  0.006833
53      Druhi Chakraborty  0.006617
175           Hanya Batra  0.005274
73         Devika Nambiar  0.005182
30         SAMAD MOHAMMED  0.005176
23            Shubh dixit  0.005140
142             Shatakshi  0.004394
62           Shreyas Mene  0.004351
10              Agam Sahu  0.004317
125  Nimish Ratan Tilwani  0.004203

Alpha=0.85
                   Person        PR
59   Sai Akshay Oggisetty  0.010298
62           Shreyas Mene  0.008038
73         Devika Nambiar  0.007924
175           Hanya Batra  0.007600
53      Druhi Chakraborty  0.007474
45     Joel Joseph Philip  0.007138
30         SAMAD MOHAMMED  0.006841
23            Shubh dixit  0.006534
142             Shatakshi  0.006206
123      Abhishek Avasthi  0.005942

Alpha=0.95
                      Person        PR
59      Sai Akshay Oggisetty  0.010579
62              Shreyas Mene  0.009467
73            Devika Nambiar  0.008602
45        Joel Joseph Philip  0.008189
393            Nishita Singh  0.008053
175              Hanya Batra  0.007950
123         Abhishek Avasthi  0.007007
395             Sartaj Singh  0.006898
432   VAISHNAV BHARAT GOPALE  0.006874
443  Rushikesh Vitthal Barge  0.006698