In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (91 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/laleshkumar/Python_course/.venv/lib/python3.14/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/laleshkumar/Python_course/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/laleshkumar/Python_course/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp314-cp314-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 325.2 kB/s  0:00:32 eta 0:00:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Successfully installed pandas-2.3.3 pytz-2025.2 tzdata-2025.2

In [2]:
import pandas as pd

In [3]:
data=[1,2,3,4,5]
series=pd.Series(data)
print("series\n",series)

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
### create series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
## Dataframe
## create a dataframe from dict of list 
data={
    'Name':['lalesh','john','jack'],
    'Age':[20,10,15],
    'city':['A','B','C']
}
pd.DataFrame(data)

     Name  Age city
0  lalesh   20    A
1    john   10    B
2    jack   15    C

In [3]:
## create a Data frame from the list of  dictionaries 
data=[
    {'Name':'Lalesh','Age':20,'City':'stm'},
    {'Name':'rajesh','Age':25,'City':'patna'},
    {'Name':'Naman','Age':19,'City':'kolkata'},
   
    
]
df=pd.DataFrame(data)
print(df)

     Name  Age     City
0  Lalesh   20      stm
1  rajesh   25    patna
2   Naman   19  kolkata

In [32]:
df=pd.read_csv('sales_data.csv')
print(df.head())  # first 5 rows
df.describe()

         date     product     category   price  quantity  revenue
0  2022-01-01  Smartphone  Electronics   600.0      10.0   6000.0
1  2022-01-01      Laptop  Electronics  1200.0       5.0   6000.0
2  2022-01-02     T-Shirt     Clothing    20.0      50.0   1000.0
3  2022-01-03  Headphones  Electronics   100.0      20.0   2000.0
4  2022-01-04     T-Shirt     Clothing    20.0      25.0    500.0

             price    quantity      revenue
count   367.000000  368.000000   368.000000
mean    211.226158   14.565217  2060.679348
std     227.335170    8.595740  1910.930790
min      20.000000    3.000000   300.000000
25%      50.000000    8.000000   800.000000
50%     100.000000   12.000000  1200.000000
75%     300.000000   20.000000  2400.000000
max    1200.000000   50.000000  7200.000000

In [12]:
df.loc[0] ## shows row

date         2022-01-01
product      Smartphone
category    Electronics
price             600.0
quantity           10.0
revenue          6000.0
Name: 0, dtype: object

In [14]:
df.iloc[1] ## index

date         2022-01-01
product          Laptop
category    Electronics
price            1200.0
quantity            5.0
revenue          6000.0
Name: 1, dtype: object

In [18]:
## Accessing specified element
data={
    'Name':['lalesh','john','jack'],
    'Age':[20,30,15],
    'city':['A','B','C']
}
df=pd.DataFrame(data)
df['Name']

0    lalesh
1      john
2      jack
Name: Name, dtype: object

In [19]:
df.at[1,'Age']

np.int64(30)

In [20]:
## Accesssing a specified element using iat
df.iat[2,2]

'C'

In [21]:
### DATA manupulation with DataFarame
df['Salary']=[50000,60000,70000]
print(df)

     Name  Age city  Salary
0  lalesh   20    A   50000
1    john   30    B   60000
2    jack   15    C   70000

In [25]:
## Remove a coloumn
df.drop('Salary',axis=1,inplace=True) ## axis=0  by default it checks in row if 
## we write axis=1 it checks in coloumn
## drop is not permanent so we have to do inplace=True

In [30]:
df

     Name  Age city
0  lalesh   23    A
1    john   33    B
2    jack   18    C

In [31]:
### Add age to the coloumn
df['Age']=df['Age']+1
df

     Name  Age city
0  lalesh   24    A
1    john   34    B
2    jack   19    C